"""empty message

Revision ID: 741091a857db
Revises: 7cbd40fcf9dc
Create Date: 2022-04-07 11:18:08.372147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741091a857db'
down_revision = '7cbd40fcf9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('det_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'det_qty')
    # ### end Alembic commands ###
